# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 2

.k_bv
   prepz q0
   prepz q1
   h q0
   h q1
   cz q0,q1
   h q0
   h q1
   x q0
   x q1
   h q1
   cnot q0,q1
   h q1
   x q0
   x q1
   h q0
   h q1
   measure q0
   measure q1
display